-- minetest.register_abm({
--     label = "Tree growth",
--     nodenames = {"group:tree_growth"},
--     interval = 10,
--     chance = 1,
--     action = function(pos, node, active_object_count, active_object_count_wider)
--         if node.name == "cicrev:log" then
--             pos.y = pos.y + 1
--             if minetest.get_node(pos).name == "air" then
--                 minetest.set_node(pos, {name = "cicrev:leaves"})
--             end
--         end
--     end,
-- })
