schematic = {
	size = {x=3, y=3, z=3},
	yslice_prob = {
		{ypos=0, prob=254},
		{ypos=1, prob=254},
		{ypos=2, prob=254},
	},
	data = {
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
		{name="cicrev:water_source", prob=254, param2=0},
	},
}
